### PR TITLE
2 - setup React extension

### PR DESCRIPTION
**Pull request by pkrp**
### Task Description
Setup React project, add basic dependencies, add SCSS linter

### CODE REVIEW

**Comment by pkrp** [comment]
[Setup React project](https://trello.com/c/l8NCMomf/2-setup-react-project)

**Comment by pkrp** [comment]
[Setup React project](https://trello.com/c/l8NCMomf/2-setup-react-project)

**Comment by pkrp** [comment]
[Setup React project](https://trello.com/c/l8NCMomf/2-setup-react-project)

**Comment by ouykjh** [comment]
Could you check eslinter one more time? It will be great to run it from command line

**Pull request merged**
